// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type PostsRole string

const (
	PostsRoleAdmin   PostsRole = "admin"
	PostsRoleAuthor  PostsRole = "author"
	PostsRoleVisitor PostsRole = "visitor"
)

func (e *PostsRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostsRole(s)
	case string:
		*e = PostsRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PostsRole: %T", src)
	}
	return nil
}

type NullPostsRole struct {
	PostsRole PostsRole `json:"posts_role"`
	Valid     bool      `json:"valid"` // Valid is true if PostsRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostsRole) Scan(value interface{}) error {
	if value == nil {
		ns.PostsRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostsRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostsRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostsRole), nil
}

type Category struct {
	CategoryID  int32  `json:"category_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Comment struct {
	CommentID int32        `json:"comment_id"`
	PostID    int32        `json:"post_id"`
	UserID    int32        `json:"user_id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Customer struct {
	CustomerID int32          `json:"customer_id"`
	Name       sql.NullString `json:"name"`
	Phone      string         `json:"phone"`
	Email      sql.NullString `json:"email"`
}

type Post struct {
	PostID    int32        `json:"post_id"`
	UserID    int32        `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Role      PostsRole    `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type PostCategory struct {
	PostID     int32 `json:"post_id"`
	CategoryID int32 `json:"category_id"`
}

type PostTag struct {
	PostID int32 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

type Tag struct {
	TagID int32  `json:"tag_id"`
	Name  string `json:"name"`
}

type User struct {
	UserID       int32        `json:"user_id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	LastLogin    sql.NullTime `json:"last_login"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
