// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (sql.Result, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteCategory(ctx context.Context, categoryID int32) error
	DeletePost(ctx context.Context, postID int32) error
	FetchUsers(ctx context.Context) ([]FetchUsersRow, error)
	GetCategories(ctx context.Context) ([]Category, error)
	GetCategory(ctx context.Context, categoryID int32) (Category, error)
	GetComment(ctx context.Context, commentID int32) (GetCommentRow, error)
	GetComments(ctx context.Context) (GetCommentsRow, error)
	GetPost(ctx context.Context, postID int32) (GetPostRow, error)
	GetPosts(ctx context.Context) ([]GetPostsRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (sql.Result, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
